### PR TITLE
Patch cbc 2.9.8

### PR DESCRIPTION
**Pull request by goxberry**
This pull request accomplishes a few things:

- Adds .gitignore files for all of the libraries vendored into PIPS so that build products and installations are ignored; these commits remove a lot of noise from invocations of `git status`
- Changes the wget script for Cbc to download version 2.7.5, which is a version known to be compatible with PIPS
- Adds patches to Cbc 2.7.5 for PIPS compatibility
- Automates the patching process in the wget script

Note: This patch breaks Clang compatibility, because Cbc 2.7.5 does not build with Clang. I can try to forward-port the patches forward to Cbc 2.7.6, but then I will have to forward-port other source files as well.

### CODE REVIEW

**Comment by goxberry** [comment]
@cnpetra @fqiang @deepakrajan Please review this PR before merging, since I know it will break Clang compatibility.

**Comment by fqiang** [comment]
@goxberry is it possible to have the clang working as well before merging?

**Comment by goxberry** [comment]
@fqiang All right, should be ready to go with clang using Cbc 2.7.6. Please test this out by compiling with clang on OS X.

cc: @cnpetra @deepakrajan

**Comment by goxberry** [comment]
I still get an error when I test this on my computer; the problem is that Cbc 2.7.6 doesn't build on clang without errors. I'll see if I can find a version later in the 2.7.x series that does build with clang. If it's not too much work, we might still be able to patch these errors in a reasonable amount of time.

**Comment by goxberry** [comment]
@fqiang I tested this pull request on Linux (with gcc 4.4.7) and OS X (with AppleClang 7.0.2 on OS X 10.10), and it worked on both operating systems. Please test this pull request out for yourself, and let me know if you encounter any problems. If everything works, this pull request should be good to merge.

cc: @cnpetra @deepakrajan

**Pull request merged**
