### PR TITLE
Fix/mumps

### PR DESCRIPTION
**Pull request by gollnlp**
Fixed a bug in the computation of the sparsified SC that was occurring when the SC terms were having different sparsity patterns.

There are two main cases the fix needs to be tested with
1. sparsity pattern of SC term on rank 0 includes the sparsity patterns of SC terms on all other ranks. This is tested thoroughly.
2. at least one SC term on a non-zero rank has a nonzero entry not present in the SC term on rank 0. This will trigger a GatherV (tested) and a sparsity pattern merge (only unit tested)

@michel2323 : Can you please help me with an example for Test 2? For example, in the driver.jl that you provided me, can you move scenario 1 (which always run on rank 0 and has a SC term with sparsity pattern that includes those of all other SC terms) to being the last scenario in the problem (so that it will fall on a non-zero rank with 
> mpiexec -n 8 julia driver.jl 1 7
)?

TO DO: remove debugging output

### CODE REVIEW

**Comment by michel2323** [comment]
I moved the base case from scenario k=0 to the last scenario k=K. So far so good. I'll try bigger cases on Theta while leaving the base case last in line.

**Comment by cnpetra** [comment]
> I moved the base case from scenario k=0 to the last scenario k=K and reran mpiexec -n 8 julia driver.jl 1 7. So far so good. I'll try bigger cases on Theta while leaving the base case last in line.

great. can you push the new driver.jl in the bug branch. I would like to test it myself...

**Comment by michel2323** [comment]
Done

**Comment by cnpetra** [comment]
thanks, I tested it and works. Also, I confirm that the root rank only Gatherv elements at the first iteration and reuses the sparsity pattern at subsequent iterations (important for performance).

**Pull request merged**
