### PR TITLE
fix bugs & changes to the CMakeList.txt

### PR DESCRIPTION
**Pull request by nychiang**
Hi Guys,

I did following changes:
1)fix bugs in PIPS-NLP; 
2)remove UMfpack from dependency and set configuration for PIPS_BUILD_TARGET=PIPS-NLP

I guess you may want to have a look of case 2) which I modified the CMakeLists.txt a little bit.
BTW, is UMfpack used in PIPS-S? If not, I think we can remove all the corresponding lines from CMakeLists.txt.

Cheers,

NY

### CODE REVIEW

**Comment by cnpetra** [comment]
Hi Naiyuan,

Not used at all. Feel free to remove the commented lines and merge. It looks good.

Cosmin

**Comment by goxberry** [comment]
@nychiang I agree with @cnpetra that you should just delete those lines instead of commenting them out.

Could you split up your commit so that each changeset does one thing?

**Comment by goxberry** [comment]
@nychiang To elaborate: splitting up your commits makes it easier to review (concerns are separated, so I know which parts are PIPS-NLP bugfixes and which parts are removing UMFPACK as a dependency). Also, in the event that a commit introduces a bug and needs to be reverted, it's better to revert one logical unit (say, PIPS-NLP bug fixes) versus many (PIPS-NLP bugfixes, removing UMFPACK as a dependency, and the PIPS-NLP buildsystem improvements).

**Comment by goxberry** [comment]
Re: UMFPACK as a dependency, was UMFPACK a hard dependency of PIPS-NLP, or a soft dependency? What is PIPS-NLP using instead of UMFPACK?

**Comment by goxberry** [comment]
As for the build system part, how do you guys envision people building PIPS? For instance, when we finally put PIPS-SBB through review, it would be useful to @deepakrajan and I to have a "PIPS-S only" build option. Do you guys envision it being useful to have a "PIPS-NLP only" build option? Is a "PIPS-IPM only" build option useful? If so, should we start thinking about all possible combinations?

What does PIPS-NLP depend on? Right now, the "PIPS-NLP only" build option is still checking for things that I don't think PIPS-NLP depends on, like CBC.

**Comment by nychiang** [comment]
Let me close this request and submit two seperate requests.
@goxberry 
UMFPACK is a soft dependency, it is only called if reduced space decomposition is used. 
However, currently I haven't fully upload reduced space decomposition source code onto the repos, hence I think we can firstly remove UMfpack. This will make users much easier to complie PIPS-NLP.

PIPS-NLP for parallel needs to use some matrix functions via COIN_LIBS. I understand this is not an ideal way to include COIN-LIBs, but we can just leave CBC as its dependency.  

I add the option PIPS-NLP only because that this is useful for me and Victor's students.

NY

**Pull request closed without merging**
